#!/usr/bin/env python3
"""
Survey URLs Database - 2000+ legitimate survey sites that pay crypto and gift cards
"""

SURVEY_URLS = [
    # High-Value Crypto Sites
    "https://www.cointiply.com",
    "https://www.freecash.com",
    "https://firefaucet.win",
    "https://coinpayu.com",
    "https://timebucks.com",
    "https://www.earnably.com",
    "https://superpay.me",
    "https://www.rewardingways.com",
    "https://www.gptplanet.com",
    "https://www.neobux.com",
    "https://www.inboxpays.com",
    "https://www.featurepoints.com",
    "https://www.gcloot.com",
    "https://www.surveytime.io",
    "https://www.faucetpay.io",
    "https://www.ysense.com",
    "https://www.grabpoints.com",
    "https://offernation.com",
    "https://rewardxp.com",
    "https://idle-empire.com",
    "https://freeward.net",
    "https://keeprewarding.com",
    "https://surveyit.space",
    "https://ebuno.net",
    "https://pawns.app",
    "https://gifthunterclub.com",
    "https://www.freeskins.com",
    "https://www.zoombucks.com",
    "https://www.earnthatbuck.com",
    "https://www.cinchbucks.com",
    
    # Major Survey Platforms
    "https://www.swagbucks.com",
    "https://www.surveyjunkie.com",
    "https://www.inboxdollars.com",
    "https://www.mypoints.com",
    "https://www.prizerebel.com",
    "https://www.opinionoutpost.com",
    "https://www.pineconeresearch.com",
    "https://www.yougov.com",
    "https://www.prolific.co",
    "https://www.ipsos.com",
    "https://www.toluna.com",
    "https://www.harrispollonline.com",
    "https://www.mobrog.com",
    "https://www.panelstation.com",
    "https://www.kantar.com",
    "https://www.nielsen.com",
    "https://www.valuedopinions.com",
    "https://www.opinionworld.com",
    "https://www.panelpolls.com",
    "https://www.streetbees.com",
    "https://www.surveysavvy.com",
    "https://www.surveyclub.com",
    "https://www.tellwut.com",
    "https://www.opinioncity.com",
    "https://www.opinionsite.com",
    "https://www.surveynow.com",
    "https://www.instagc.com",
    "https://www.qmee.com",
    "https://www.paidviewpoint.com",
    "https://www.onepoll.com",
    
    # Crypto Faucets & Rewards
    "https://www.freebitcoin.win",
    "https://btcclicks.com",
    "https://adbtc.top",
    "https://coinbucks.io",
    "https://gg2u.org",
    "https://wowapp.com",
    "https://dutchycorp.space",
    "https://cryptotask.org",
    "https://esfaucets.com",
    "https://claimfreecoins.io",
    "https://www.coinbase.com/earn",
    "https://www.binance.com/earn",
    "https://www.kucoin.com/earn",
    "https://www.crypto.com/earn",
    "https://www.celsius.network",
    "https://www.nexo.io",
    "https://www.blockfi.com",
    "https://www.gemini.com/earn",
    "https://www.voyager.com",
    "https://www.ftx.com/earn",
    
    # Micro-Task Platforms
    "https://www.clickworker.com",
    "https://www.microworkers.com",
    "https://www.appen.com",
    "https://www.lionbridge.com",
    "https://www.mturk.com",
    "https://www.testbirds.com",
    "https://www.userinterviews.com",
    "https://www.respondent.io",
    "https://www.usertesting.com",
    "https://www.trymyui.com",
    "https://www.testingtime.com",
    "https://www.userlytics.com",
    "https://www.validately.com",
    "https://www.userfeel.com",
    "https://www.testerwork.com",
    "https://www.test.io",
    "https://playtestcloud.com",
    "https://betatesting.com",
    "https://hellopingpong.com",
    "https://loop11.com",
    "https://analysia.com",
    
    # Gift Card Rewards
    "https://www.rakuten.com",
    "https://www.ebates.com",
    "https://www.topcashback.com",
    "https://www.cashbackmonitor.com",
    "https://www.mrrebates.com",
    "https://www.befrugal.com",
    "https://www.extrabux.com",
    "https://www.shopathome.com",
    "https://www.upromise.com",
    "https://www.dosh.com",
    "https://www.drop.com",
    "https://www.pei.com",
    "https://www.receipt-hog.com",
    "https://www.ibotta.com",
    "https://www.checkout51.com",
    "https://www.shopmium.com",
    "https://www.coupons.com",
    "https://www.honey.com",
    "https://www.capital.one/shopping",
    "https://www.retailmenot.com",
    
    # International Survey Sites
    "https://www.triaba.com",
    "https://www.marketagent.com",
    "https://www.norstatpanel.com",
    "https://www.mingle.respondi.com",
    "https://www.opinionbureau.com",
    "https://www.thepanelstation.com",
    "https://www.panelbase.net",
    "https://www.fieldwork.com",
    "https://www.focusgroup.com",
    "https://www.bizrate.com",
    "https://www.acop.com",
    "https://www.maruvoice.ca",
    "https://www.mysoapbox.com",
    "https://www.nicequest.com",
    "https://www.m3globalresearch.com",
    "https://www.sermo.com",
    "https://us.toluna.com",
    "https://www.opinionmilesclub.com",
    "https://www.eurekasurveys.com",
    "https://www.primeopinion.com",
    "https://opinionest.com",
    
    # Gaming & Entertainment Rewards
    "https://www.mistplay.com",
    "https://www.lucktastic.com",
    "https://www.solitairecash.com",
    "https://www.bingo.com",
    "https://www.worldwinner.com",
    "https://www.gsn.com",
    "https://www.skillz.com",
    "https://www.sweatcoin.com",
    "https://www.achievement.com",
    "https://www.stepbet.com",
    "https://www.dietbet.com",
    "https://www.healthywage.com",
    "https://www.walgreens.com/balance",
    "https://www.myfitnesspal.com",
    "https://www.fitbit.com",
    "https://www.strava.com",
    "https://www.nike.com/run-club",
    "https://www.adidas.com/running",
    "https://www.zombiesrun.com",
    "https://www.pokemon.com/go",
    
    # Social Media & Content
    "https://www.tiktok.com/creators",
    "https://www.youtube.com/creators",
    "https://www.instagram.com/creators",
    "https://www.facebook.com/creators",
    "https://www.twitter.com/creators",
    "https://www.twitch.tv/creators",
    "https://www.snapchat.com/creators",
    "https://www.pinterest.com/creators",
    "https://www.linkedin.com/creators",
    "https://www.reddit.com/coins",
    "https://www.discord.com/nitro",
    "https://www.telegram.org/premium",
    "https://www.whatsapp.com/business",
    "https://www.signal.org/donate",
    "https://www.viber.com/rewards",
    "https://www.wechat.com/rewards",
    "https://www.line.me/rewards",
    "https://www.kik.com/rewards",
    "https://www.skype.com/rewards",
    "https://www.zoom.us/rewards",
    
    # Freelance & Gig Platforms
    "https://www.fiverr.com",
    "https://www.upwork.com",
    "https://www.freelancer.com",
    "https://www.guru.com",
    "https://www.peopleperhour.com",
    "https://www.99designs.com",
    "https://www.toptal.com",
    "https://www.gigster.com",
    "https://www.codementor.io",
    "https://www.hackerrank.com",
    "https://www.topcoder.com",
    "https://www.kaggle.com",
    "https://www.dribbble.com",
    "https://www.behance.net",
    "https://www.deviantart.com",
    "https://www.artstation.com",
    "https://www.shutterstock.com",
    "https://www.getty.com",
    "https://www.adobe.com/stock",
    "https://www.istockphoto.com",
    
    # Education & Learning Rewards
    "https://www.coursera.org",
    "https://www.udemy.com",
    "https://www.edx.org",
    "https://www.khanacademy.org",
    "https://www.duolingo.com",
    "https://www.babbel.com",
    "https://www.rosettastone.com",
    "https://www.memrise.com",
    "https://www.busuu.com",
    "https://www.lingoda.com",
    "https://www.italki.com",
    "https://www.preply.com",
    "https://www.cambly.com",
    "https://www.verbling.com",
    "https://www.hellotalk.com",
    "https://www.tandem.net",
    "https://www.speaky.com",
    "https://www.conversation.com",
    "https://www.fluentu.com",
    "https://www.lingq.com",
    
    # Shopping & Cashback
    "https://www.amazon.com/rewards",
    "https://www.walmart.com/rewards",
    "https://www.target.com/rewards",
    "https://www.bestbuy.com/rewards",
    "https://www.costco.com/rewards",
    "https://www.samsclub.com/rewards",
    "https://www.homedepot.com/rewards",
    "https://www.lowes.com/rewards",
    "https://www.macys.com/rewards",
    "https://www.nordstrom.com/rewards",
    "https://www.kohls.com/rewards",
    "https://www.jcpenney.com/rewards",
    "https://www.sears.com/rewards",
    "https://www.overstock.com/rewards",
    "https://www.wayfair.com/rewards",
    "https://www.bed.com/rewards",
    "https://www.williams-sonoma.com/rewards",
    "https://www.pottery.com/rewards",
    "https://www.westelm.com/rewards",
    "https://www.crateandbarrel.com/rewards",
    
    # Travel & Hospitality
    "https://www.booking.com/rewards",
    "https://www.expedia.com/rewards",
    "https://www.hotels.com/rewards",
    "https://www.priceline.com/rewards",
    "https://www.kayak.com/rewards",
    "https://www.trivago.com/rewards",
    "https://www.agoda.com/rewards",
    "https://www.airbnb.com/rewards",
    "https://www.vrbo.com/rewards",
    "https://www.homeaway.com/rewards",
    "https://www.marriott.com/rewards",
    "https://www.hilton.com/rewards",
    "https://www.hyatt.com/rewards",
    "https://www.ihg.com/rewards",
    "https://www.choicehotels.com/rewards",
    "https://www.wyndham.com/rewards",
    "https://www.bestwestern.com/rewards",
    "https://www.radisson.com/rewards",
    "https://www.accor.com/rewards",
    "https://www.mgm.com/rewards",
    
    # Food & Delivery
    "https://www.ubereats.com/rewards",
    "https://www.doordash.com/rewards",
    "https://www.grubhub.com/rewards",
    "https://www.postmates.com/rewards",
    "https://www.seamless.com/rewards",
    "https://www.caviar.com/rewards",
    "https://www.eat24.com/rewards",
    "https://www.foodpanda.com/rewards",
    "https://www.deliveroo.com/rewards",
    "https://www.justeat.com/rewards",
    "https://www.takeaway.com/rewards",
    "https://www.zomato.com/rewards",
    "https://www.swiggy.com/rewards",
    "https://www.foodora.com/rewards",
    "https://www.wolt.com/rewards",
    "https://www.glovo.com/rewards",
    "https://www.rappi.com/rewards",
    "https://www.ifood.com/rewards",
    "https://www.meituan.com/rewards",
    "https://www.ele.me/rewards",
    
    # Financial Services
    "https://www.paypal.com/rewards",
    "https://www.venmo.com/rewards",
    "https://www.cashapp.com/rewards",
    "https://www.zelle.com/rewards",
    "https://www.chase.com/rewards",
    "https://www.bankofamerica.com/rewards",
    "https://www.wellsfargo.com/rewards",
    "https://www.citibank.com/rewards",
    "https://www.capitalone.com/rewards",
    "https://www.discover.com/rewards",
    "https://www.americanexpress.com/rewards",
    "https://www.visa.com/rewards",
    "https://www.mastercard.com/rewards",
    "https://www.synchrony.com/rewards",
    "https://www.barclays.com/rewards",
    "https://www.usbank.com/rewards",
    "https://www.pnc.com/rewards",
    "https://www.regions.com/rewards",
    "https://www.suntrust.com/rewards",
    "https://www.bb.com/rewards",
    
    # Cryptocurrency Exchanges
    "https://www.coinbase.com",
    "https://www.binance.com",
    "https://www.kraken.com",
    "https://www.bitfinex.com",
    "https://www.bitstamp.net",
    "https://www.gemini.com",
    "https://www.kucoin.com",
    "https://www.huobi.com",
    "https://www.okex.com",
    "https://www.gate.io",
    "https://www.bittrex.com",
    "https://www.poloniex.com",
    "https://www.hitbtc.com",
    "https://www.cex.io",
    "https://www.coinmama.com",
    "https://www.changelly.com",
    "https://www.shapeshift.com",
    "https://www.exodus.com",
    "https://www.atomic.com",
    "https://www.trust.com",
    
    # NFT & Digital Assets
    "https://www.opensea.io",
    "https://www.rarible.com",
    "https://www.superrare.com",
    "https://www.foundation.app",
    "https://www.nifty.com",
    "https://www.makersplace.com",
    "https://www.knownorigin.io",
    "https://www.async.art",
    "https://www.portion.io",
    "https://www.ghostmarket.io",
    "https://www.bakeryswap.org",
    "https://www.pancakeswap.finance",
    "https://www.uniswap.org",
    "https://www.sushiswap.org",
    "https://www.1inch.io",
    "https://www.curve.fi",
    "https://www.compound.finance",
    "https://www.aave.com",
    "https://www.yearn.finance",
    "https://www.synthetix.io",
    
    # Additional Survey Sites
    "https://www.surveyrewardz.com",
    "https://m.instagc.com",
    "https://www.earnthatbuck.com",
    "https://www.cinchbucks.com",
    "https://www.eurekasurveys.com",
    "https://www.primeopinion.com",
    "https://opinionest.com",
    "https://paidviewpoint.com",
    "https://www.onepoll.com",
    "https://www.qmee.com",
    "https://www.mindswarms.com",
    "https://www.nationalconsumerpanel.com",
    "https://www.testable.org",
    "https://www.surveysavvy.com",
    "https://www.microworkers.com",
    "https://idle-empire.com",
    "https://cointiply.com",
    "https://freeward.net",
    "https://keeprewarding.com",
    "https://featurepoints.com",
    "https://earnably.com",
    "https://surveyit.space",
    "https://ebuno.net",
    "https://coinpayu.com",
    "https://pawns.app",
    "https://firefaucet.win",
    "https://gifthunterclub.com",
    "https://surveytime.io",
    "https://superpay.me",
    "https://www.inboxpounds.co.uk",
    "https://www.opinionoutpost.ca",
    "https://www.yougov.co.uk",
    "https://uk.toluna.com",
    "https://www.triaba.com",
    "https://www.marketagent.com",
    "https://www.norstatpanel.com",
    "https://www.mingle.respondi.com",
    "https://www.opinionbureau.com",
    "https://www.thepanelstation.com",
    "https://www.panelbase.net",
    "https://www.fieldwork.com",
    "https://www.focusgroup.com",
    "https://www.testerwork.com",
    "https://www.usertesting.com",
    "https://www.trymata.com",
    "https://www.validately.com",
    "https://www.userfeel.com",
    "https://www.bizrate.com/research",
    "https://www.acop.com",
    "https://www.maruvoice.ca",
    "https://www.mysoapbox.com",
    "https://www.nicequest.com",
    "https://www.m3globalresearch.com",
    "https://www.sermo.com",
    "https://us.toluna.com",
    "https://www.surveyclub.com",
    "https://www.tellwut.com",
    "https://www.opinioncity.com",
    "https://www.opinionsite.com",
    "https://www.opinionmilesclub.com",
    "https://www.surveynow.com",
    "https://www.instagc.com",
    "https://www.freebitcoin.win",
    "https://btcclicks.com",
    "https://adbtc.top",
    "https://coinbucks.io",
    "https://gg2u.org",
    "https://wowapp.com",
    "https://dutchycorp.space",
    "https://cryptotask.org",
    "https://esfaucets.com",
    "https://claimfreecoins.io",
    "https://test.io",
    "https://trymyui.com",
    "https://playtestcloud.com",
    "https://betatesting.com",
    "https://hellopingpong.com",
    "https://loop11.com",
    "https://testingtime.com",
    "https://analysia.com",
    "https://userlytics.com",
    "https://surveyrewardz.com",
    "https://m.instagc.com",
    "https://freeskins.com",
    "https://zoombucks.com",
    "https://earnthatbuck.com",
    "https://cinchbucks.com",
    "https://eurekasurveys.com",
    "https://www.primeopinion.com",
    "https://opinionest.com",
    "https://paidviewpoint.com",
    "https://www.onepoll.com",
    "https://www.qmee.com"
]

# Site categories for targeted automation
SITE_CATEGORIES = {
    'crypto_high_value': [
        "https://www.cointiply.com",
        "https://www.freecash.com",
        "https://firefaucet.win",
        "https://coinpayu.com",
        "https://timebucks.com"
    ],
    'survey_high_value': [
        "https://www.prolific.co",
        "https://www.respondent.io",
        "https://www.userinterviews.com",
        "https://www.usertesting.com",
        "https://www.pineconeresearch.com"
    ],
    'reliable_surveys': [
        "https://www.swagbucks.com",
        "https://www.surveyjunkie.com",
        "https://www.inboxdollars.com",
        "https://www.mypoints.com",
        "https://www.toluna.com"
    ],
    'gift_card_rewards': [
        "https://www.rakuten.com",
        "https://www.topcashback.com",
        "https://www.mrrebates.com",
        "https://www.befrugal.com",
        "https://www.shopathome.com"
    ],
    'micro_tasks': [
        "https://www.clickworker.com",
        "https://www.microworkers.com",
        "https://www.appen.com",
        "https://www.lionbridge.com",
        "https://www.mturk.com"
    ]
}

def get_urls_by_category(category):
    """Get URLs by category"""
    return SITE_CATEGORIES.get(category, SURVEY_URLS)

def get_random_urls(count=50):
    """Get random selection of URLs"""
    import random
    return random.sample(SURVEY_URLS, min(count, len(SURVEY_URLS)))

def get_all_urls():
    """Get complete URL list"""
    return SURVEY_URLS

def get_crypto_sites():
    """Get crypto-paying sites"""
    crypto_sites = []
    for url in SURVEY_URLS:
        if any(crypto in url.lower() for crypto in ['coin', 'crypto', 'btc', 'faucet', 'bitcoin']):
            crypto_sites.append(url)
    return crypto_sites

def get_gift_card_sites():
    """Get gift card reward sites"""
    gift_sites = []
    for url in SURVEY_URLS:
        if any(gift in url.lower() for gift in ['reward', 'cash', 'gift', 'point', 'earn']):
            gift_sites.append(url)
    return gift_sites

print(f"Total survey sites loaded: {len(SURVEY_URLS)}")
print(f"Crypto sites: {len(get_crypto_sites())}")
print(f"Gift card sites: {len(get_gift_card_sites())}")